### PR TITLE
Style fix

### PR DESCRIPTION
**Pull request by manifestoso**
Atom feed header rendering correction. 
Author items are documented all together under _data/authors.yml for easy management.

### CODE REVIEW

**Comment by LeNPaul** [comment]
I looked at the file changes and it looks like you added the 'title' and 'description' of the site to the config.yml file - was this intentional?

**Comment by manifestoso** [comment]
@LeNPaul <code>title:</code> and <code>description:</code> fileds can be used to customise feed.xml, which can be different to <code>{{ site.data.settings.title }}</code> if chosen to be. 
My apologies, it seems that I forgot to comment the function ;) 
If <code>title:</code> and <code>description:</code> in *_config.yml* left out, feed will use <code>{{ site.data.settings.title }}</code>. So in a nutshell, those two fileds are optional but nice to have.

**Review by manifestoso — COMMENTED** [review]
provides feed icon at header and footer

**Review by manifestoso — COMMENTED** [review]
The separation of authors from _data/settings allows authors info to live at a central place for easy maintenance and collaboration.

**Comment by LeNPaul** [comment]
I like the idea of putting the authors in a separate file! I'll merge this pull request, but I might make some changes. I really want to try to avoid hard coding anything into the code, but for now it should be fine. Thanks!

**Pull request merged**
